/// <reference types="tree-sitter-cli/dsl" />
// @ts-check

module.exports = grammar({
  name: 'plantuml',

  extras: $ => [/\s/, $.comment],
  rules: {
    diagram: $ =>
      choice(
        $.uml,
        $.json,
        $.yaml,
        $.json,
        $.yaml,
        $.ebnf,
        $.regex,
        $.ditaa,
        $.gantt,
        $.chronology,
        $.mindmap,
        $.wbs,
        $.chen,
      ),
    uml: $ => seq('@startuml', repeat($.expression), '@enduml'),
    expression: $ => choice($.sequence_diagram, $.attribute),
    attribute: $ =>
      choice(
        prec.left(
          seq(
            'autonumber',
            choice('inc', 'resume'),
            choice(/\d+\.\d+\.\d/, optional($.string)),
            /\w/,
          ),
        ),
        seq('autonumber', repeat(/\d+/)),
        'autonumber stop',
        seq(
          alias(
            choice(
              'participant',
              'actor',
              'boundary',
              'control',
              'entity',
              'database',
              'collections',
              'queue',
            ),
            $.kind,
          ),
          alias($.participant_name, $.name),
          repeat(choice(seq('#', $.color), $.attr_order, $.attr_alias)),
        ),
      ),
    attr_alias: $ => seq('as', alias(/\w+/, $.new_name)),
    attr_order: $ => seq('order', /\d+/),
    string: $ => seq('"', repeat(choice(/[^"]/, '\\"')), '"'),
    participant_name: $ => choice(/\w+/, $.string),
    sequence_diagram: $ =>
      seq(
        alias($.participant_name, $.left),
        choice(
          alias('->', $.to_right),
          alias('-->', $.to_right_dotted),
          alias('<-', $.to_left),
          alias('<--', $.to_left_dotted),
        ),
        alias($.participant_name, $.right),
        optional(seq(':', alias(/[^\r?\n]+/, $.activity))),
      ),

    json: $ => create_non_uml($, 'json'),
    yaml: $ => create_non_uml($, 'yaml'),
    ebnf: $ => create_non_uml($, 'ebnf'),
    regex: $ => create_non_uml($, 'regex'),
    ditaa: $ => create_non_uml($, 'ditaa'),
    gantt: $ => create_non_uml($, 'gantt'),
    chronology: $ => create_non_uml($, 'chronology'),
    mindmap: $ => create_non_uml($, 'mindmap'),
    wbs: $ => create_non_uml($, 'wbs'),
    chen: $ => create_non_uml($, 'chen'),
    comment: $ =>
      choice(
        seq("'", /[^\r\n]*\r?\n/),
        seq("/'", repeat(/[^'],"'"/), prec(1, token("'/"))),
      ),

    color: $ =>
      token(
        choice(
          /[0-9a-fA-F]{3,6}/,
          /[0-9a-fA-F]{8}/,
          /transparent/i,
          /transparent black/i,
          // https://www.w3.org/TR/css-color-4/#named-colors
          /aliceblue/i,
          /antiquewhite/i,
          /aqua/i,
          /aquamarine/i,
          /azure/i,
          /beige/i,
          /bisque/i,
          /black/i,
          /blanchedalmond/i,
          /blue/i,
          /blueviolet/i,
          /brown/i,
          /burlywood/i,
          /cadetblue/i,
          /chartreuse/i,
          /chocolate/i,
          /coral/i,
          /cornflowerblue/i,
          /cornsilk/i,
          /crimson/i,
          /cyan/i,
          /darkblue/i,
          /darkcyan/i,
          /darkgoldenrod/i,
          /darkgray/i,
          /darkgreen/i,
          /darkgrey/i,
          /darkkhaki/i,
          /darkmagenta/i,
          /darkolivegreen/i,
          /darkorange/i,
          /darkorchid/i,
          /darkred/i,
          /darksalmon/i,
          /darkseagreen/i,
          /darkslateblue/i,
          /darkslategray/i,
          /darkslategrey/i,
          /darkturquoise/i,
          /darkviolet/i,
          /deeppink/i,
          /deepskyblue/i,
          /dimgray/i,
          /dimgrey/i,
          /dodgerblue/i,
          /firebrick/i,
          /floralwhite/i,
          /forestgreen/i,
          /fuchsia/i,
          /gainsboro/i,
          /ghostwhite/i,
          /gold/i,
          /goldenrod/i,
          /gray/i,
          /green/i,
          /greenyellow/i,
          /grey/i,
          /honeydew/i,
          /hotpink/i,
          /indianred/i,
          /indigo/i,
          /ivory/i,
          /khaki/i,
          /lavender/i,
          /lavenderblush/i,
          /lawngreen/i,
          /lemonchiffon/i,
          /lightblue/i,
          /lightcoral/i,
          /lightcyan/i,
          /lightgoldenrodyellow/i,
          /lightgray/i,
          /lightgreen/i,
          /lightgrey/i,
          /lightpink/i,
          /lightsalmon/i,
          /lightseagreen/i,
          /lightskyblue/i,
          /lightslategray/i,
          /lightslategrey/i,
          /lightsteelblue/i,
          /lightyellow/i,
          /lime/i,
          /limegreen/i,
          /linen/i,
          /magenta/i,
          /maroon/i,
          /mediumaquamarine/i,
          /mediumblue/i,
          /mediumorchid/i,
          /mediumpurple/i,
          /mediumseagreen/i,
          /mediumslateblue/i,
          /mediumspringgreen/i,
          /mediumturquoise/i,
          /mediumvioletred/i,
          /midnightblue/i,
          /mintcream/i,
          /mistyrose/i,
          /moccasin/i,
          /navajowhite/i,
          /navy/i,
          /oldlace/i,
          /olive/i,
          /olivedrab/i,
          /orange/i,
          /orangered/i,
          /orchid/i,
          /palegoldenrod/i,
          /palegreen/i,
          /paleturquoise/i,
          /palevioletred/i,
          /papayawhip/i,
          /peachpuff/i,
          /peru/i,
          /pink/i,
          /plum/i,
          /powderblue/i,
          /purple/i,
          /rebeccapurple/i,
          /red/i,
          /rosybrown/i,
          /royalblue/i,
          /saddlebrown/i,
          /salmon/i,
          /sandybrown/i,
          /seagreen/i,
          /seashell/i,
          /sienna/i,
          /silver/i,
          /skyblue/i,
          /slateblue/i,
          /slategray/i,
          /slategrey/i,
          /snow/i,
          /springgreen/i,
          /steelblue/i,
          /tan/i,
          /teal/i,
          /thistle/i,
          /tomato/i,
          /turquoise/i,
          /violet/i,
          /wheat/i,
          /white/i,
          /whitesmoke/i,
          /yellow/i,
          /yellowgreen/i,
          // https://www.w3schools.com/colors/colors_names.asp
          /AliceBlue/i,
          /AntiqueWhite/i,
          /Aqua/i,
          /Aquamarine/i,
          /Azure/i,
          /Beige/i,
          /Bisque/i,
          /Black/i,
          /BlanchedAlmond/i,
          /Blue/i,
          /BlueViolet/i,
          /Brown/i,
          /BurlyWood/i,
          /CadetBlue/i,
          /Chartreuse/i,
          /Chocolate/i,
          /Coral/i,
          /CornflowerBlue/i,
          /Cornsilk/i,
          /Crimson/i,
          /Cyan/i,
          /DarkBlue/i,
          /DarkCyan/i,
          /DarkGoldenRod/i,
          /DarkGray/i,
          /DarkGrey/i,
          /DarkGreen/i,
          /DarkKhaki/i,
          /DarkMagenta/i,
          /DarkOliveGreen/i,
          /DarkOrange/i,
          /DarkOrchid/i,
          /DarkRed/i,
          /DarkSalmon/i,
          /DarkSeaGreen/i,
          /DarkSlateBlue/i,
          /DarkSlateGray/i,
          /DarkSlateGrey/i,
          /DarkTurquoise/i,
          /DarkViolet/i,
          /DeepPink/i,
          /DeepSkyBlue/i,
          /DimGray/i,
          /DimGrey/i,
          /DodgerBlue/i,
          /FireBrick/i,
          /FloralWhite/i,
          /ForestGreen/i,
          /Fuchsia/i,
          /Gainsboro/i,
          /GhostWhite/i,
          /Gold/i,
          /GoldenRod/i,
          /Gray/i,
          /Grey/i,
          /Green/i,
          /GreenYellow/i,
          /HoneyDew/i,
          /HotPink/i,
          /IndianRed/i,
          /Indigo/i,
          /Ivory/i,
          /Khaki/i,
          /Lavender/i,
          /LavenderBlush/i,
          /LawnGreen/i,
          /LemonChiffon/i,
          /LightBlue/i,
          /LightCoral/i,
          /LightCyan/i,
          /LightGoldenRodYellow/i,
          /LightGray/i,
          /LightGrey/i,
          /LightGreen/i,
          /LightPink/i,
          /LightSalmon/i,
          /LightSeaGreen/i,
          /LightSkyBlue/i,
          /LightSlateGray/i,
          /LightSlateGrey/i,
          /LightSteelBlue/i,
          /LightYellow/i,
          /Lime/i,
          /LimeGreen/i,
          /Linen/i,
          /Magenta/i,
          /Maroon/i,
          /MediumAquaMarine/i,
          /MediumBlue/i,
          /MediumOrchid/i,
          /MediumPurple/i,
          /MediumSeaGreen/i,
          /MediumSlateBlue/i,
          /MediumSpringGreen/i,
          /MediumTurquoise/i,
          /MediumVioletRed/i,
          /MidnightBlue/i,
          /MintCream/i,
          /MistyRose/i,
          /Moccasin/i,
          /NavajoWhite/i,
          /Navy/i,
          /OldLace/i,
          /Olive/i,
          /OliveDrab/i,
          /Orange/i,
          /OrangeRed/i,
          /Orchid/i,
          /PaleGoldenRod/i,
          /PaleGreen/i,
          /PaleTurquoise/i,
          /PaleVioletRed/i,
          /PapayaWhip/i,
          /PeachPuff/i,
          /Peru/i,
          /Pink/i,
          /Plum/i,
          /PowderBlue/i,
          /Purple/i,
          /RebeccaPurple/i,
          /Red/i,
          /RosyBrown/i,
          /RoyalBlue/i,
          /SaddleBrown/i,
          /Salmon/i,
          /SandyBrown/i,
          /SeaGreen/i,
          /SeaShell/i,
          /Sienna/i,
          /Silver/i,
          /SkyBlue/i,
          /SlateBlue/i,
          /SlateGray/i,
          /SlateGrey/i,
          /Snow/i,
          /SpringGreen/i,
          /SteelBlue/i,
          /Tan/i,
          /Teal/i,
          /Thistle/i,
          /Tomato/i,
          /Turquoise/i,
          /Violet/i,
          /Wheat/i,
          /White/i,
          /WhiteSmoke/i,
          /Yellow/i,
          /YellowGreen/i,
        ),
      ),
  },
});

function create_non_uml($, ty) {
  return seq(
    token(`@start${ty}`),
    alias(repeat(choice('@', /[^@]/)), $[`${ty}_data`]),
    token(prec(1, `@end${ty}`)),
    repeat(/\r?\n/),
  );
}
